### ISSUE TITLE
Not able to find the binaries required

### ISSUE THREAD

**Issue by nitesh-acog** [PatrickPenner/fast_grow_server#1]
I am not able to find those binaries you mentioned in your repo , clipper, preprocessor, databasebuilder,

**Comment by tonyzhu2021** [comment]
I am not able to find those binaries you mentioned in your repo , clipper, preprocessor, databasebuilder,too

**Comment by PatrickPenner** [comment]
There is an external dependency on C++ binaries to run core server functionality. I unfortunately also do not have access to that code base anymore after having changed jobs.
